import { Metadata } from 'next';
import { TheHeader } from './components/TheHeader';
import { TheFooter } from './components/TheFooter';
import './globals.css';

export const metadata: Metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <TheHeader />
        <main className='container p-4 border-1 mx-auto min-h-screen'>{children}</main>
        <TheFooter />
      </body>
    </html>
  );
}
